### ISSUE TITLE
about weights

### ISSUE THREAD

**Issue by qq3399476669** [Hope1337/YOWOv3#20]
Thank you for your work. Do you have yolov8.pth weights? All I found are. pt weights

**Comment by Hope1337** [comment]
@qq3399476669 It seems like you have some confusion, I have already published all the weights in .pth format for YOLOv8 here: https://huggingface.co/manh6054/YOWOv3/tree/main/weights/backbone2D/YOLOv8

**Comment by qq3399476669** [comment]
Thank you for your reply. The project code uses the weight in the pth format. Later, it can be changed to the weight in the pt format.

![image](https://github.com/user-attachments/assets/6bc0c92a-0ef0-4984-abd1-0e15e16f312d)

**Comment by qq3399476669** [comment]
> @qq3399476669 It seems like you have some confusion, I have already published all the weights in .pth format for YOLOv8 here: https://huggingface.co/manh6054/YOWOv3/tree/main/weights/backbone2D/YOLOv8

Thank you for your reply. The project code uses the weight in the pth format. Later, it can be changed to the weight in the pt format.
![image](https://github.com/user-attachments/assets/5d3dc08b-fda7-46a8-b5d6-d0bbffed6faf)
