### ISSUE TITLE
Question About Action classes in custom Training Videos

### ISSUE THREAD

**Issue by pingchesu** [Hope1337/YOWOv3#21]
Hi,

First off, thank you for your excellent implementation of the YOWO3 model! I have a question regarding the structure of the training dataset and would appreciate your advice.

In my project, I’m working with three action classes:

Pick items
Hold items
Drop items
Each video contains all three actions in sequence. I’m wondering whether I should split each video into three separate sub-videos (one for each action, similar to the UCF dataset), or if it’s better to use the entire video sequence for training.

What would be the best approach for optimal performance?

Thank you in advance!

**Comment by Hope1337** [comment]
@pingchesu YOWOv3 only use sequence of 16 frame as input, not whole video. You can annotate for each image (bounding boxes and class) and just load 16 frame (with the last frame is the annotated one) to train.

**Comment by joesu-angible** [comment]
> @pingchesu YOWOv3 only use sequence of 16 frame as input, not whole video. You can annotate for each image (bounding boxes and class) and just load 16 frame (with the last frame is the annotated one) to train.

@Hope1337 
Thank you for the clarification, and I apologize for not being clearer in my initial question.

I’m following the UCF101_24 dataset structure, where the folder hierarchy is like:
```bash
./labels/category/video_id/frame_0001.txt ~ frame_1000.txt
```
and each video contains a single action category. However, in my case, each video may include up to three different action categories.

Should I split the video into subcategories like:
```bash
./labels/category1/video1_category1/frame_0001~0100.txt
./labels/category2/video1_category2/frame_0101~0500.txt
./labels/category3/video1_category3/frame_0500~1000.txt
```
Or is it acceptable to keep all categories in one sequence, like:
```bash
./labels/video1/frame_0001~1000.txt
```
I plan to modify the dataset loader for my needs, but I want to ensure that combining multiple categories within a single video makes sense in this context. Any advice would be appreciated!

**Comment by pingchesu** [comment]
> @pingchesu YOWOv3 only use sequence of 16 frame as input, not whole video. You can annotate for each image (bounding boxes and class) and just load 16 frame (with the last frame is the annotated one) to train.

@Hope1337 
Thank you for the response! I apologize for not being clearer in my initial question.
I understand that YOWO3 uses sequences of 16 frames as input, but my question is more focused on the dataset structure. My training dataset is modeled after the UCF101_24 dataset, where the folder structure looks like:
```bash
./labels/category/video_id/frame_0001.txt ~ frame_1000.txt
```
In this setup, each video only contains one action category. However, in my case, each video may contain up to three different action categories.

Should I split each video into separate subcategories like:
```bash
./labels/category1/video1_category1/frame_0001~0100.txt
./labels/category2/video1_category2/frame_0101~0500.txt
./labels/category3/video1_category3/frame_0500~1000.txt
```
Or would it be valid to keep all categories within one sequence, like:
```bash
./labels/video1/frame_0001~1000.txt
```
I plan to modify the dataset loader to accommodate my data, but I’d like to know if it makes sense to include multiple categories in a single video for training. Any guidance would be appreciated!

**Comment by Hope1337** [comment]
@pingchesuI think you should maintain the format ```./labels/category1/video1_category1/frame_0001~0100.txt```

The reason for this lies in when you are testing the model, there will be questions like "Oh, why does the model predict so poorly for class A". You can entirely rely on the folder for class A and experiment with it. It's mainly for convenience.

**Comment by Eurekaer** [comment]
@pingchesu Hi, Recently, I also want to customize a dataset for training. Could you please tell me how you specifically followed the UCF dataset format when customizing your dataset? Are there any tutorials or materials you can share? Thank you very much!

**Comment by pingchesu** [comment]
Hi @Eurekaer,

I’m using CVAT to annotate my custom dataset. CVAT allows you to upload entire videos and use the tracking mode for video annotation. After annotation, I typically export the dataset in formats like COCO or Datumaro, and then I write a custom script to convert it into the UCF format.

Here are some tutorials and resources that might help you:

[Track Mode Basics in CVAT](https://docs.cvat.ai/docs/manual/basics/track-mode-basics/)
[Data Export Video Tutorial](https://docs.cvat.ai/docs/manual/advanced/formats/#data-export-video-tutorial)
[CVAT YouTube Channel](https://www.youtube.com/@cvat-ai/videos)
[Create an Annotation Task](https://docs.cvat.ai/docs/manual/basics/create_an_annotation_task/)
I hope this helps!

**Comment by Eurekaer** [comment]
Hi @pingchesu,
Thank you very much for your reply, it has been very helpful to me. I wish you a pleasant life!

**Comment by Eurekaer** [comment]
Hi @pingchesu,
I have a question I would like to consult with you. When I used CVAT to obtain COCO format annotations and converted them to UCF format, I found some discrepancies (in the UCF101-24 dataset). Therefore, I would like to ask whether the bbox format in UCF annotations is [x1, y1, x2, y2]? Did you convert it from the COCO format [x, y, width, height]? Thank you!

**Comment by pingchesu** [comment]
@Eurekaer
Sure. The UCF101-24 is [x1, y1, x2, y2], so if i use coco format, I will convert it from [x, y, width, height] to [x1, y1, x2, y2]. Recently I am using Datumaro format, because it more compatible with CVAT. If you have any question, please feel free to reply the message!

[Datumaro](https://github.com/openvinotoolkit/datumaro)

**Comment by Eurekaer** [comment]
@pingchesu 
Thank you very much for your reply, it has been very helpful to me. I wish you a happy life!
