### ISSUE TITLE
Question About Model Performance

### ISSUE THREAD

**Issue by fkrdnjs** [Hope1337/YOWOv3#27]
Thank you for sharing such a good repo.
![Screenshot](https://github.com/user-attachments/assets/df552ca2-e251-4084-b5eb-0416b6507c8b)

The model shows high mAP performance on the UCF101-24 dataset, but the performance is lower on the AVAv2.2 dataset. Could you explain why this is the case?

Is this model more suitable for action recognition than action detection?
Thank you very much for your help.

**Comment by Hope1337** [comment]
@fkrdnjs AVAv2 is a dramatically imbalance dataset, some classes have few thousand instance while some have >= 100K.

**Comment by fkrdnjs** [comment]
Thank you for your reply.

You provide various pre-trained models, and I am curious whether these models were trained on datasets like ImageNet or if they are models where the weights were randomly initialized.

**Comment by Hope1337** [comment]
@fkrdnjs I used the pretrained version provided by corresponding author of it.

**Comment by fkrdnjs** [comment]
Thank you very much for your quick response.
