### ISSUE TITLE
ONNX export

### ISSUE THREAD

**Issue by Hook35** [Hope1337/YOWOv3#9]
Hi, 

I want to export my trained model to onnx. How can I do it?

Thx.

**Comment by Hope1337** [comment]
Hi, thank you for asking.

I'm going to add a guide for it after finishing the YOWOv3 paper, at least after the paper deadline at the end of this month (August).

**Comment by Hope1337** [comment]
@Hook35 Hi, I have just added ONNX export and announced it in [#13](https://github.com/Hope1337/YOWOv3/issues/13)
